name: Test

on:
  push:
  pull_request:
  
jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tz:
          - "Africa/Bamako"
          - "America/St_Thomas"
          - "UTC"
          - "Europe/Berlin"
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - run: |
        make test
      env:
        TZ: ${{ matrix.tz }}
    - run: cat build/results/*txt
    - name: Check results and set pipeline status
      run: |
        # Directory to check
        DIR_TO_CHECK="build/results"

        # Search for files containing the text "FAIL"
        if grep -rq "FAIL" "$DIR_TO_CHECK"; then
          echo "A file contains the text 'FAIL'."
          exit 1
        else
          echo "No files with the text 'FAIL' found."
          exit 0
        fi
